services:
  db:
    image: 'postgres:latest'
    container_name: 'postgres-container'
    environment:
      POSTGRES_DB: dormitorydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'
  pgadmin:
    image: 'elestio/pgadmin'
    container_name: 'pgadmin-container'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password123
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
