services:
  db:
    image: 'postgres:latest'
    container_name: 'postgres-container'
    restart: always
    environment:
      POSTGRES_DB: dormitory
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: 'elestio/pgadmin'
    container_name: 'pgadmin-container'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'springboot-container'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dormitory
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./src/main:/app/src/main
    restart: always

volumes:
  postgres_data:

